Repository 300CIS017-Object-Oriented-Programming/proyecto-3-test, pull requests merged in 2024-11, with the labels that each got.

#8 version actualizada
  src/app.py
Labels: enhancement

#13 12-correcion-separacion-pestanas - correcion de errores para la separ…
  src/app.py
Labels: bug

#21 20-separacion-por-ventanas-actualizado - NEW: implementacion visual d…
  src/app.py
  src/carga.py
  src/gestor_archivos.py
Labels: enhancement, invalid

#25 24-correcion-de-errores-parte-visual - FIX: se arreglo una serie de p…
  pages/visualizacion.py
  src/app.py
  src/carga.py
  src/filtrado.py
  src/utils.py
  src/visualizacion.py
Labels: enhancement

#34 33-cambio-en-el-filtrado-de-datos-utilizando-bien-el-controller - FIX…
  src/filtrado.py
Labels: bug, wontfix

#38 33-cambio-en-el-filtrado-de-datos-utilizando-bien-el-controller - FIX…
  src/filtrado.py
Labels: enhancement
